{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"ODI_Match_Data\",\"ODI_Match_info\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.1004.0 (24.11)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "2b7aef9d-072a-4810-9117-042cb2a12be7",
        "fromColumn": "start_date",
        "fromTable": "ODI_Match_Data",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c6b6fd64-1606-4ac3-897f-adf9968a8b49"
      },
      {
        "name": "43c9f046-afbb-4b12-9dad-6c9a5d15cefe",
        "fromColumn": "date",
        "fromTable": "ODI_Match_info",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_36f91687-1e1a-4d44-9f1d-8242ac106b2a"
      },
      {
        "name": "436693f8-cd85-44ae-85c1-1d8dd5719f94",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "match_id",
        "fromTable": "ODI_Match_Data",
        "toColumn": "id",
        "toTable": "ODI_Match_info"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "ODI_Match_Data",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "match_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d3ec1bea-98d2-4002-9a15-70066d035421",
            "sourceColumn": "match_id",
            "summarizeBy": "none"
          },
          {
            "name": "season",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8ed6f28-2ca6-4427-9823-4350d2552b4a",
            "sourceColumn": "season",
            "summarizeBy": "none"
          },
          {
            "name": "start_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "528d6838-c860-40b7-bc99-8c19279da236",
            "sourceColumn": "start_date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c6b6fd64-1606-4ac3-897f-adf9968a8b49"
                },
                "isDefault": true,
                "relationship": "2b7aef9d-072a-4810-9117-042cb2a12be7"
              }
            ]
          },
          {
            "name": "venue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a9b2214-afb7-44ae-a1dc-90f26ce53080",
            "sourceColumn": "venue",
            "summarizeBy": "none"
          },
          {
            "name": "innings",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "33d6360b-120d-483b-91ac-38450aa94c1f",
            "sourceColumn": "innings",
            "summarizeBy": "sum"
          },
          {
            "name": "ball",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "342e23d9-a0a0-4e26-a578-68542fde4a61",
            "sourceColumn": "ball",
            "summarizeBy": "sum"
          },
          {
            "name": "batting_team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9351cbf6-64ab-4068-88fe-8b7af615f004",
            "sourceColumn": "batting_team",
            "summarizeBy": "none"
          },
          {
            "name": "bowling_team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7012b8da-acf8-4074-953c-d48e3e70af8d",
            "sourceColumn": "bowling_team",
            "summarizeBy": "none"
          },
          {
            "name": "striker",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "786daa9e-f1b0-4f0f-80c6-99e0b3956f3a",
            "sourceColumn": "striker",
            "summarizeBy": "none"
          },
          {
            "name": "non_striker",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ee03669b-30d9-4272-9718-5fbf6545b2ae",
            "sourceColumn": "non_striker",
            "summarizeBy": "none"
          },
          {
            "name": "bowler",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb950829-90dd-4176-9417-53b1cd040baa",
            "sourceColumn": "bowler",
            "summarizeBy": "none"
          },
          {
            "name": "runs_off_bat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0cb546b9-b8f9-4264-8cc7-8613f4f01907",
            "sourceColumn": "runs_off_bat",
            "summarizeBy": "sum"
          },
          {
            "name": "extras",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "516b64de-1ad6-49c9-83da-0e77cf9e681d",
            "sourceColumn": "extras",
            "summarizeBy": "sum"
          },
          {
            "name": "wides",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "84571d5a-ad71-4356-a882-c7a33174085f",
            "sourceColumn": "wides",
            "summarizeBy": "sum"
          },
          {
            "name": "noballs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4aa71a9d-0191-4b50-a7cd-0ce10a405044",
            "sourceColumn": "noballs",
            "summarizeBy": "sum"
          },
          {
            "name": "byes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57d2ecc5-7f8b-41f2-a1f3-581c0435ba00",
            "sourceColumn": "byes",
            "summarizeBy": "none"
          },
          {
            "name": "legbyes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7098660e-77f4-4823-87fb-561e13593dd4",
            "sourceColumn": "legbyes",
            "summarizeBy": "none"
          },
          {
            "name": "penalty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "288e6980-d5cc-4026-b416-128cf8200d89",
            "sourceColumn": "penalty",
            "summarizeBy": "none"
          },
          {
            "name": "wicket_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "64d87895-5c0b-4b2c-b2c6-f848d8819382",
            "sourceColumn": "wicket_type",
            "summarizeBy": "none"
          },
          {
            "name": "player_dismissed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f87970c0-55c3-4280-8ecd-29db297169e7",
            "sourceColumn": "player_dismissed",
            "summarizeBy": "none"
          },
          {
            "name": "other_wicket_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4a351aab-5c0a-4b71-ba2c-f57c4f8698f8",
            "sourceColumn": "other_wicket_type",
            "summarizeBy": "none"
          },
          {
            "name": "other_player_dismissed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f207ec6f-b9ea-46b2-af93-ccc4f4146274",
            "sourceColumn": "other_player_dismissed",
            "summarizeBy": "none"
          },
          {
            "name": "cricsheet_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "370c1270-3a5d-46cc-9048-0e258068fcf2",
            "sourceColumn": "cricsheet_id",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "f70c83de-7ab4-47bc-a7f1-64ca733b8528",
        "measures": [
          {
            "name": "0",
            "expression": "0",
            "formatString": "0",
            "lineageTag": "cfaa439b-8ef9-4d0e-a2b6-ada5bc5e059b"
          },
          {
            "name": "100",
            "expression": "100",
            "formatString": "0",
            "lineageTag": "3fd742bb-f05a-457f-8d00-6fce72f3583c"
          }
        ],
        "partitions": [
          {
            "name": "ODI_Match_Data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"D:\\powerbi project\\cricket\\ODI_Match_Data.csv\"),[Delimiter=\",\", Columns=23, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"match_id\", Int64.Type}, {\"season\", type text}, {\"start_date\", type date}, {\"venue\", type text}, {\"innings\", Int64.Type}, {\"ball\", type number}, {\"batting_team\", type text}, {\"bowling_team\", type text}, {\"striker\", type text}, {\"non_striker\", type text}, {\"bowler\", type text}, {\"runs_off_bat\", Int64.Type}, {\"extras\", Int64.Type}, {\"wides\", Int64.Type}, {\"noballs\", Int64.Type}, {\"byes\", type text}, {\"legbyes\", type text}, {\"penalty\", type text}, {\"wicket_type\", type text}, {\"player_dismissed\", type text}, {\"other_wicket_type\", type text}, {\"other_player_dismissed\", type text}, {\"cricsheet_id\", Int64.Type}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"Kennington Oval, London\",\"Kennington Oval\",Replacer.ReplaceText,{\"venue\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Lord's, London\",\"Lord's,\",Replacer.ReplaceText,{\"venue\"})",
                "in",
                "    #\"Replaced Value1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_aa2ef67d-821e-4af8-8dd9-59958b50c730",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f9460ca1-32fb-4814-b80d-720812b5e5df",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "e1c81f7a-fb4d-449e-8613-cb00e541db17",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "28589113-fd33-4d2c-930b-a28852f8a8f0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "a478c663-f89b-41fc-9231-bed781152f1b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "5b29dd61-5f5c-414e-a032-11ec0443fa94",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "bdb0864c-de1a-47e4-bfff-c3c8176ae038",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "a58c09d6-d700-4ed6-9578-626833f4265f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "01b408a7-b974-4375-a6f5-8230a3e4bd99",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "ff20d27b-b3b0-4085-abfc-706ebf63d929",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "300bc7ae-3d55-46e9-b5c7-3c90ec6a2094",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b4e633e3-9f62-4a9e-a50a-a5ddaa9998b7",
                "ordinal": 3
              }
            ],
            "lineageTag": "7a5bfad1-4927-4cf9-bfba-3911b1a8007f"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "32c2157c-3ca3-462b-9a41-c223aa42f34c",
        "partitions": [
          {
            "name": "DateTableTemplate_aa2ef67d-821e-4af8-8dd9-59958b50c730",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_c6b6fd64-1606-4ac3-897f-adf9968a8b49",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6f0f0d97-d9be-48a0-bcb5-4f2407808e14",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "3ab9bd23-3ef3-40c9-888c-c16fefd79c45",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "bcceb0be-9d65-4d6e-bac3-865a6113dc86",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "2d0ddf0d-b036-4749-a1c6-f15a02c7c1ac",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "015cde25-6d6d-404c-91b8-c18ad813645a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "73bbd786-f8dd-415c-98f4-da881a200536",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "c5a67b20-ebb7-4e4a-92f5-82876cf4e384",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "95393fd4-f90a-402d-b4ff-9e92a3b07dda",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "53779cb6-5cc9-4be6-9c8e-161289b696e5",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "76b72317-4873-4451-945c-fcd3c3f75db2",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "bde7e699-877e-47af-8f15-a07c0eeb221a",
                "ordinal": 3
              }
            ],
            "lineageTag": "2e60ea0f-3a9a-409b-8a39-8314a9b3c52a"
          }
        ],
        "isHidden": true,
        "lineageTag": "7d4e147e-f650-48a9-9f9e-563c76b3407c",
        "partitions": [
          {
            "name": "LocalDateTable_c6b6fd64-1606-4ac3-897f-adf9968a8b49",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ODI_Match_Data'[start_date])), 1, 1), Date(Year(MAX('ODI_Match_Data'[start_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "ODI_Match_info",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ee1b16f8-533f-44ae-8edb-c9f3d335a175",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "season",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75ba09c2-0269-4042-b9fb-19c823889097",
            "sourceColumn": "season",
            "summarizeBy": "none"
          },
          {
            "name": "city",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c290045a-d708-4869-85da-71b5f703ba52",
            "sourceColumn": "city",
            "summarizeBy": "none"
          },
          {
            "name": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1c5ad1ad-26fc-433a-8fc5-b40e683ab27d",
            "sourceColumn": "date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_36f91687-1e1a-4d44-9f1d-8242ac106b2a"
                },
                "isDefault": true,
                "relationship": "43c9f046-afbb-4b12-9dad-6c9a5d15cefe"
              }
            ]
          },
          {
            "name": "team1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b37b048-c648-407b-9360-c0c3d1732bdb",
            "sourceColumn": "team1",
            "summarizeBy": "none"
          },
          {
            "name": "team2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "056ffa7b-3f79-44f5-9b0d-376ed6369ca1",
            "sourceColumn": "team2",
            "summarizeBy": "none"
          },
          {
            "name": "toss_winner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4dcd0e8d-92e4-49ff-8aca-034be62fcc94",
            "sourceColumn": "toss_winner",
            "summarizeBy": "none"
          },
          {
            "name": "toss_decision",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39279ce4-bb95-4d44-9449-f2e034bf7aa4",
            "sourceColumn": "toss_decision",
            "summarizeBy": "none"
          },
          {
            "name": "result",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ee4bba5e-e208-46ca-a1e3-4d1e0e4889e6",
            "sourceColumn": "result",
            "summarizeBy": "none"
          },
          {
            "name": "dl_applied",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0e5ff218-122d-47ee-a4e8-ed725a5d24bd",
            "sourceColumn": "dl_applied",
            "summarizeBy": "sum"
          },
          {
            "name": "winner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "20cdfe65-3047-4b58-8b02-3ba0f0816b2a",
            "sourceColumn": "winner",
            "summarizeBy": "none"
          },
          {
            "name": "win_by_runs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "59d5ce43-1e37-42be-91db-e63d3aacf1d0",
            "sourceColumn": "win_by_runs",
            "summarizeBy": "sum"
          },
          {
            "name": "win_by_wickets",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4b91e8eb-9f02-476e-a40a-f1bf0a65dda1",
            "sourceColumn": "win_by_wickets",
            "summarizeBy": "sum"
          },
          {
            "name": "player_of_match",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7bef1fbf-8698-4ba7-b3de-df440714dfe3",
            "sourceColumn": "player_of_match",
            "summarizeBy": "none"
          },
          {
            "name": "venue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "573f3503-5443-441e-9a7a-e51b65fe3aea",
            "sourceColumn": "venue",
            "summarizeBy": "none"
          },
          {
            "name": "umpire1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51e8d94c-e4b4-4606-a522-ebf2463331d0",
            "sourceColumn": "umpire1",
            "summarizeBy": "none"
          },
          {
            "name": "umpire2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98b3d1ff-3422-4716-8c81-961094bee126",
            "sourceColumn": "umpire2",
            "summarizeBy": "none"
          },
          {
            "name": "umpire3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "976727fe-0c63-445d-ab85-4aa197640efe",
            "sourceColumn": "umpire3",
            "summarizeBy": "none"
          },
          {
            "name": "IndianMatches",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "CALCULATETABLE(",
              "    VALUES(ODI_Match_info[venue]),",
              "    ODI_Match_info[team1] = \"India\" || ODI_Match_info[team2] = \"India\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "da867866-b912-4e30-bb19-3ccb6ea7d971",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "IndiaOpponentWins",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    (ODI_Match_info[team1] = \"India\" || ODI_Match_info[team2] = \"India\"),",
              "    ODI_Match_info[winner],",
              "    BLANK()",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "0c300f70-5ae8-4e8c-8cb9-a0ebf94fd572",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "IndiaOpponent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    ODI_Match_info[team1] = \"India\" || ODI_Match_info[team2] = \"India\",",
              "    IF(ODI_Match_info[team1] = \"India\", ODI_Match_info[team2], ODI_Match_info[team1]),",
              "    BLANK()",
              ")",
              ""
            ],
            "lineageTag": "491e914f-86d0-4a9f-b55a-5abfe6c13571",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "WinPercentage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(COUNTROWS(ODI_Match_info), ODI_Match_info[winner] = \"India\"),",
              "    CALCULATE(COUNTROWS(ODI_Match_info), ODI_Match_info[team1] = \"India\" || ODI_Match_info[team2] = \"India\"),",
              "    ",
              "    /*CALCULATE(COUNTROWS(ODI_Match_info)),*/",
              "    0",
              ")",
              "    "
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isDataTypeInferred": true,
            "lineageTag": "cc62f7ed-efdf-48bf-9d43-1ab558765c02",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "IndiaWins",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    (ODI_Match_info[team1] = \"India\" || ODI_Match_info[team2] = \"India\") && ODI_Match_info[winner]= \"India\",",
              "    ODI_Match_info[winner],",
              "    BLANK()",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "4defb7da-d821-4e6e-b1a0-756a1136c9fa",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "5baae569-b009-423a-8e56-88ab96d1768d",
        "measures": [
          {
            "name": "prediction",
            "expression": [
              "/*CALCULATE(ODI_Match_info[IndiaWins] not null)",
              "*/",
              "DIVIDE(",
              "    COUNTROWS(FILTER('ODI_Match_info', NOT(ISBLANK('ODI_Match_info'[IndiaWins])))),",
              "    COUNTROWS(ALLSELECTED('ODI_Match_info')),",
              "    0",
              ") * 100"
            ],
            "formatString": "0.00",
            "lineageTag": "50f2afe8-daff-4b4f-80ca-63467a0b9034"
          },
          {
            "name": "win%",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR __BASELINE_VALUE = COUNTA('ODI_Match_info'[winner])",
              "VAR __VALUE_TO_COMPARE = COUNTA('ODI_Match_info'[IndiaWins])",
              "RETURN",
              "\tIF(",
              "\t\tNOT ISBLANK(__VALUE_TO_COMPARE),",
              "\t\tDIVIDE(__VALUE_TO_COMPARE - __BASELINE_VALUE, __BASELINE_VALUE)",
              "\t)"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "MathematicalPercentageDifference",
                  "version": 0
                }
              }
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "247a6536-b696-4e15-91e5-25d94d386072"
          },
          {
            "name": "PercentageOfTotal",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "IF(",
              "    COUNTROWS(FILTER('ODI_Match_info', NOT(ISBLANK('ODI_Match_info'[IndiaWins])))) > 0,",
              "    DIVIDE(",
              "        COUNTROWS(FILTER('ODI_Match_info', NOT(ISBLANK('ODI_Match_info'[IndiaWins])))),",
              "        COUNTROWS(ALLSELECTED('ODI_Match_info')),",
              "        0",
              "    ),",
              "    0",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "PercentageDifferenceFrom",
                  "version": 0
                }
              }
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "adf5ab3e-bdda-4281-8d6c-f9bd52c1a280"
          }
        ],
        "partitions": [
          {
            "name": "ODI_Match_info",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"D:\\powerbi project\\cricket\\ODI_Match_info.csv\"),[Delimiter=\",\", Columns=18, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"id\", Int64.Type}, {\"season\", type text}, {\"city\", type text}, {\"date\", type date}, {\"team1\", type text}, {\"team2\", type text}, {\"toss_winner\", type text}, {\"toss_decision\", type text}, {\"result\", type text}, {\"dl_applied\", Int64.Type}, {\"winner\", type text}, {\"win_by_runs\", Int64.Type}, {\"win_by_wickets\", Int64.Type}, {\"player_of_match\", type text}, {\"venue\", type text}, {\"umpire1\", type text}, {\"umpire2\", type text}, {\"umpire3\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"Lord's, London\",\"Lord's\",Replacer.ReplaceText,{\"venue\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Kennington Oval, London\",\"Kennington Oval\",Replacer.ReplaceText,{\"venue\"})",
                "in",
                "    #\"Replaced Value1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_36f91687-1e1a-4d44-9f1d-8242ac106b2a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3284f5f6-94cf-4ac2-9449-d922e5ab4a1f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "20e8eb67-03de-4eec-8c8d-78897d519695",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "9d5dcf2c-79cb-4db4-bb30-fe2f999faf91",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "07808d03-b52e-47e5-8806-0612d52f3f99",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "0b2ac454-3840-4570-a17c-478083255e39",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "ae1ea7fa-8306-4771-902d-0442fe056cf6",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "9aca0005-540a-4c6b-984a-b1aa22d191bf",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ba5d72b1-92aa-40c1-b9bb-2f1b7a80634a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "7b00fdbe-9c76-4bfb-8564-2431e73d04d0",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6617837c-e442-4476-aebf-f6b545d62e43",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f042af51-b924-44dd-8196-7323d16fdf3b",
                "ordinal": 3
              }
            ],
            "lineageTag": "3b0bb97b-4953-42e9-992f-09872df78cb9"
          }
        ],
        "isHidden": true,
        "lineageTag": "193fd824-fff1-460b-86d5-7396407ca9dd",
        "partitions": [
          {
            "name": "LocalDateTable_36f91687-1e1a-4d44-9f1d-8242ac106b2a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ODI_Match_info'[date])), 1, 1), Date(Year(MAX('ODI_Match_info'[date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}